version: '3'
services:
  sqlserver:
      image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
      user: '0:0'
      ports:
        - 1433:1433
      environment:
        ACCEPT_EULA: Y
        SA_PASSWORD: PasswordO1.
        MSSQL_PID: Express
      volumes:
        - ~/docker/sqlserver-data:/var/opt/mssql/data
      networks:
        h5network:
          aliases:
            - h5_sqlserver
  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
      environment:
        - discovery.type=single-node
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ports:
        - 9200:9200
        - 9300:9300
      networks:
        h5network:
          aliases:
            - h5_elk
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      h5network:
        aliases:
          - h5_zookeeper

  broker:
    image: confluentinc/cp-kafka:7.3.2
    container_name: broker
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      h5network:
        aliases:
          - h5_kafka

  h5permissionapi:
    build:
      context: ./api
    image: n5api:dev
    ports:
      - '8088:80'
      - '1443:443'
    networks:
        h5network:
          aliases:
            - h5permission_api

  h5permissionapp:
    build:
      context: ./app
    image: n5app:dev
    ports:
      - '8089:80'
    networks:
        h5network:
          aliases:
            - h5permission_app
    
networks:
  h5network:
    name: h5_net
    driver: bridge
    ipam:
      driver: default